import './globals.css';
import type { Metadata } from 'next';
import { Work_Sans } from 'next/font/google';

const inter = Work_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Editors',
  description: "Generated by @masumahmedeesha.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} grid grid-cols-10`}>
        <main className="col-span-10 md:col-span-10 bg-[#F8F8F8]">
          <div className="px-3">
            {children}
          </div>
          <p className="text-[#333333] text-sm font-semibold text-opacity-50 px-8 py-4">
            Copyright © 2023 masumahmedeesha, All rights reserved.
          </p>
        </main>
      </body>
    </html>
  );
}
